#!/bin/sh
#
# Copyright (C) 2016 LEDE
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

to_hex () {
	input=$1
	hex=$(printf '0x%x' $input)
	echo $hex
}

ubootenv_mtdinfo () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	mtd_dev=$(echo $UBOOTENV_PART | awk '{print $1}' | sed 's/:$//')
	mtd_size=$(echo $UBOOTENV_PART | awk '{print "0x"$2}')
	mtd_erase=$(echo $UBOOTENV_PART | awk '{print "0x"$3}')
	nor_flash=$(find /sys/bus/spi/devices/*/mtd -name ${mtd_dev})

	if [ -n "$nor_flash" ]; then
		ubootenv_size=$mtd_size
	else
		# size is fixed to 0x40000 in u-boot
		ubootenv_size=0x40000
	fi

	sectors=$(( $ubootenv_size / $mtd_erase ))
	echo /dev/$mtd_dev 0x0 $ubootenv_size $mtd_erase $sectors
}

case "$board" in
qcom,ipq9574-ap-al02-c4)
	uboot_env_part_path=$(find_mtd_part "0:APPSBLENV")
	uboot_env_part_name=${uboot_env_part_path#"/dev/"}
	uboot_env_part_offset="$(cat /sys/block/${uboot_env_part_name}/alignment_offset)"
	uboot_env_part_size="$(blockdev --getsize64 ${uboot_env_part_path})"
	ubootenv_add_uci_config "$uboot_env_part_path" "$(to_hex "$uboot_env_part_offset")" $(to_hex "$uboot_env_part_size") $(to_hex "$uboot_env_part_size")
	;;
*)
	uboot_env_part_path=$(find_mmc_part "0:APPSBLENV")
	uboot_env_part_name=${uboot_env_part_path#"/dev/"}
	uboot_env_part_offset="$(cat /sys/block/mmcblk*/${uboot_env_part_name}/alignment_offset)"
	uboot_env_part_size="$(blockdev --getsize64 ${uboot_env_part_path})"
	ubootenv_add_uci_config "$uboot_env_part_path" "$(to_hex "$uboot_env_part_offset")" $(to_hex "$uboot_env_part_size") $(to_hex "$uboot_env_part_size")
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
