#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017-2019 The Linux Foundation. All rights reserved.
# Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

START=00
STOP=95

create_soft_link()
{
	if [ -e /sys/firmware/devicetree/base/MP_256 ]; then
		cp -f $*
	elif [ ! -e /sys/firmware/devicetree/base/MP_256 ]; then
		ln -s $*
	fi
}

caldata_symlink_creation(){
	var=0
	while read -r line
	do
		board=$(echo $line | cut -f1 -d',')
		if [[ "$board" == "$1" ]]; then
			var=$((var+1))
			if [[ $var == $2 ]]; then
				local brdid=$(echo $line | cut -f2 -d',')
				local art_slot=$(echo $line | cut -f3 -d',')
				local pciid=$(echo $line | cut -f6 -d',')
				break
			fi
		fi
	done < /lib/firmware/ftm.conf

	if [ -e /lib/firmware/qcn9224/caldata_$art_slot.b$brdid ]; then
			ln -sf /lib/firmware/qcn9224/caldata_$art_slot.b$brdid cal-pci-000$pciid:01:00.0.bin
	fi
}

get_partname() {
	local part_name=""
	local parse_value=4
	local mtdpart=$(grep "\"0:BOOTCONFIG\"" /proc/mtd | awk -F: '{print $1}')
	local trymode_inprogress=$(cat /sys/devices/platform/firmware:scm/trymode_inprogress)

	dd if=/dev/${mtdpart} of=/tmp/bootconfig.bin

	dumpimage -b $parse_value &> /dev/null
	if [[ "$?" == 1 ]];then
		echo "Unable to read bootconfig"
		return 1
	fi

	if [ ! -e /tmp/bootconfig_members.txt ]; then
		echo " Parsed bootconfig info not available "
		return 1
	fi

	local boot_set=$(grep "Boot-set" /tmp/bootconfig_members.txt | awk -F: '{print $2}')
	local image_status_A=$(grep "Image-set-status-A" /tmp/bootconfig_members.txt | awk -F: '{print $2}')
	local image_status_B=$(grep "Image-set-status-B" /tmp/bootconfig_members.txt | awk -F: '{print $2}')

	if [ "$boot_set" -eq 0 ] && [ "$image_status_A" -ne 0 ]; then
		part_name="1"
	elif [ "$boot_set" -eq 1 ] && [ "$image_status_B" -eq 0 ]; then
		part_name="1"
	fi

	if [ "$trymode_inprogress" -eq 1 ]; then
		if [ "$part_name" -eq "1" ]; then
			part_name=""
		else
			part_name="1"
		fi
	fi

	echo $part_name
}

get_partname_legacy() {
	local part_name=$1
	local age0=$(cat /proc/boot_info/bootconfig0/age)
	local age1=$(cat /proc/boot_info/bootconfig1/age)
	local bootname="bootconfig1"

	#Try mode
	if [ -e /proc/upgrade_info/trybit ]; then
		if [ -e /proc/upgrade_info/trymode_inprogress ]; then
			if [ $age0 -le $age1 ]; then
				bootname="bootconfig0"
			else
				bootname="bootconfig1"
			fi
		else
			if [ $age1 -ge $age0 ]; then
				bootname="bootconfig1"
			else
				bootname="bootconfig0"
			fi
		fi
	fi

	primaryboot=$(cat /proc/boot_info/$bootname/$part_name/primaryboot)
	if [ $primaryboot -eq 1 ]; then
		part_name="0:WIFIFW_1"
	fi

	echo $part_name
}


mount_wifi_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local primaryboot=""
	local part_name="0:WIFIFW"
	local ubi_part_name="rootfs"
	local arch=""
	local wifi_on_rootfs=""
	local hw=""
	local board_name
	local fwfolder="/lib/firmware"

	[ -f /tmp/sysinfo/board_name ] && {
		board_name=ap$(cat /tmp/sysinfo/board_name | awk -F 'ap' '{print$2}')
		if [ "$board_name" == "ap" ]; then
			board_name=$(cat /tmp/sysinfo/board_name | awk -F, '{print$2}')
		fi

		case $board_name in
                        *rdp*)
                        board_name=$(echo $board_name | cut -f2 -d-)
                        ;;
                esac

	}

	[ -e /sys/firmware/devicetree/base/AUTO_MOUNT ] && {
		case $board_name in
			ap-mp*)
				fwfolder="/lib/firmware/wifi"
				mkdir -p $fwfolder
			;;
		esac
	}

	if mount | grep -q WIFI_FW; then
		return 0
	fi

	arch=$1
	case "$arch" in
		"IPQ8074")
			hw="hw2.0"
	;;
		"IPQ6018")
			hw="hw1.0"
	;;
		*)
			hw="hw1.0"
	;;
	esac

	if [ "$arch" == "IPQ5424" ]; then
		local index=$(get_partname $part_name $arch)
		if [ "$index" == "1" ]; then
			part_name=${part_name}_${index}
			ubi_part_name=${ubi_part_name}_${index}
		fi
	else
		part_name=$(get_partname_legacy $part_name)
	fi

	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]] || [[ "$arch" == "IPQ5332" ]] || [[ "$arch" == "IPQ5424" ]] || [[ "$arch" == "devsoc" ]]; then
		wifi_on_rootfs="1"
	fi

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep -w "WIFIFW" | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	if [ -n "$wifi_on_rootfs" ]; then
		nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)
		if [ -n "$nand_part" ]; then
			emmc_part=""
		fi
	else
		nand_part=$(find_mtd_part $part_name 2> /dev/null)
	fi

	mkdir -p /lib/firmware/$arch/WIFI_FW
	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/WIFI_FW > /dev/kmsg 2>&1
		if [ $? -eq 0 ]; then
			cp /rom/lib/firmware/$arch/WIFI_FW/*.* /lib/firmware/$arch/WIFI_FW/
		fi
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		if [ -n "$nor_mtd_part" ]; then
			/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/WIFI_FW > /dev/kmsg 2>&1
		fi
	elif [ -n "$nand_part" ]; then
                if [ -n "$wifi_on_rootfs" ]; then
                       local PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
                else
                       local PART=$(grep -w  "$part_name" /proc/mtd | awk -F: '{print $1}')
                fi
		ubiattach -p /dev/$PART
		sync
		local ubi_part=$(find_mtd_part wifi_fw 2> /dev/null)
		if [ -n "$ubi_part" ]; then
			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/kmsg 2>&1
			if [ $? -ne 0 ]; then
				echo "WIFI FW mount failed, retry after 1 sec" > /dev/console 2>&1
				sleep 1
				/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/WIFI_FW > /dev/kmsg 2>&1
				if [ $? -ne 0 ]; then
					echo "CRITICAL:WIFI FW mount failed, after 1 sec retry" > /dev/console 2>&1
					echo $(cat /proc/mtd) > /dev/console 2>&1
					return -1
				fi
			fi
		fi
	fi
	if [ -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] || ([ -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ]); then
		echo " WIFI FW mount is successful" > /dev/console 2>&1
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9000 ]; then
		cd  $fwfolder && mkdir -p qcn9000 && mkdir -p /vendor/firmware/qcn9000
		cd qcn9000 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/*.* .
		cd /vendor/firmware/qcn9000 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/Data.msc .
		mkdir -p /lib/firmware/qcn9000 && cd /lib/firmware/qcn9000 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9224 ]; then
		cd  $fwfolder && mkdir -p qcn9224 && mkdir -p /vendor/firmware/qcn9224
		cd qcn9224 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/*.* .
		cd /vendor/firmware/qcn9224 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/Data.msc .
		ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/Data_dualmac.msc .
		mkdir -p /lib/firmware/qcn9224 && cd /lib/firmware/qcn9224 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		cd $fwfolder && mkdir -p qcn9100 && mkdir -p /vendor/firmware/qcn9100
		cd qcn9100 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn9100 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/Data.msc .
		mkdir -p /lib/firmware/qcn9100 && cd /lib/firmware/qcn9100 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9100/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6122 ]; then
		cd $fwfolder && mkdir -p qcn6122 && mkdir -p /vendor/firmware/qcn6122
		cd qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/Data.msc .
		mkdir -p /lib/firmware/qcn6122 && cd /lib/firmware/qcn6122 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn6122/qdss* .
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		cd $fwfolder && mkdir -p qcn6122 && mkdir -p /vendor/firmware/qcn6122
		cd qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6122 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/Data.msc .
		mkdir -p /lib/firmware/qcn6122 && cd /lib/firmware/qcn6122 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9100/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9160 ]; then
		cd $fwfolder && mkdir -p qcn9160 && mkdir -p /vendor/firmware/qcn9160
		cd qcn9160 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9160/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn9160 && ln -s /lib/firmware/$arch/WIFI_FW/qcn9160/Data.msc .
		mkdir -p /lib/firmware/qcn9160 && cd /lib/firmware/qcn9160 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9160/qdss* .
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6432 ]; then
		cd $fwfolder && mkdir -p qcn6432 && mkdir -p /vendor/firmware/qcn6432
		cd qcn6432 && ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/*.* . && ln -s /lib/firmware/$arch/WIFI_FW/q6_fw.* .
		cd /vendor/firmware/qcn6432 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn6432/Data.msc .
		mkdir -p /lib/firmware/qcn6432 && cd /lib/firmware/qcn6432 && create_soft_link /lib/firmware/$arch/WIFI_FW/qcn6432/qdss* .
        fi

	mkdir -p $fwfolder/$arch
	cd  $fwfolder/$arch && ln -s /lib/firmware/$arch/WIFI_FW/*.* .
	cd  /lib/firmware/$arch && create_soft_link /lib/firmware/$arch/WIFI_FW/qdss* .

	if [ -e /sys/firmware/devicetree/base/MP_512 ] || [ -e /sys/firmware/devicetree/base/MP_256 ]; then
		#qcn9224 INI file would have all QCN9224 RDP's info, so first priority for qcn9224 file if it exists
		if [ -f /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature_512P.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature_512P.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature_512P.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature_512P.ini .
		fi
	else
		#qcn9224 INI file would have all QCN9224 RDP's info, so first priority for qcn9224 file if it exists
		if [ -f /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9224/firmware_rdp_feature.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/firmware_rdp_feature.ini .
		elif [ -f /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature.ini ]; then
			cd /lib/firmware
			create_soft_link /lib/firmware/$arch/WIFI_FW/qcn9000/firmware_rdp_feature.ini .
		fi
	fi

	. /lib/read_caldata_to_fs.sh
	do_load_ipq4019_board_bin

	if [ -e /lib/firmware/$arch/WIFI_FW/board-2.bin ]; then

		case "$arch" in
			IPQ5332 |\
			IPQ5424)
				mkdir -p /lib/firmware/ath12k/$arch/$hw
				cd /lib/firmware/ath12k/$arch/$hw/
				;;
			*)
				mkdir -p /lib/firmware/ath11k/$arch/$hw
				cd /lib/firmware/ath11k/$arch/$hw/
				ln -s /lib/firmware/$arch/caldata.bin .
				;;
		esac
		ln -s /lib/firmware/$arch/WIFI_FW/board-2.bin .
		ln -s /lib/firmware/$arch/qdss_trace_config.bin .
		ln -s /lib/firmware/$arch/WIFI_FW/q6_fw*  .
		ln -s /lib/firmware/$arch/WIFI_FW/iu_fw*  .

		case $board_name in
			ap-mi01.3|ap-mi01.3-c3|ap-mi01.3-c2|ap-mi04.1|ap-mi04.1-c2|ap-mi01.2|ap-mi01.2-c2|ap-mi01.6|ap-mi01.12|ap-mi01.14|ap-mi04.3)
				#caldata.bin --> ahb 2GHz
				if [ -e /lib/firmware/IPQ5332/caldata.bin ]; then
					ln -sf /lib/firmware/IPQ5332/caldata.bin cal-ahb-c000000.wifi.bin
				fi
			;;
			*)
				#No sym links
			;;
		esac

		case $board_name in
                        rdp466 |\
			rdp487 |\
			rdp464)
                                #caldata.bin --> ahb 2GHz
                                if [ -e /lib/firmware/IPQ5424/caldata.bin ]; then
                                        ln -sf /lib/firmware/IPQ5424/caldata.bin cal-ahb-c000000.wifi.bin
                                fi
                        ;;
                        *)

                                #No sym links
                        ;;
                esac

	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6432 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn6432/board-2.bin ]; then
			mkdir -p /lib/firmware/ath12k/QCN6432/hw1.0/
			cd /lib/firmware/ath12k/QCN6432/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/board-2.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/qdss_trace_config.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6432/iu_fw* .
			ln -s /lib/firmware/$arch/WIFI_FW/q6_fw* .

			case $board_name in
				ap-mi01.3)
					#caldata_1.b0060 --> ahb 5GHz
					if [ -e /lib/firmware/qcn6432/caldata_1.b0060 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0060 cal-ahb-soc@0:wifi1@c0000000.bin
					fi

					#caldata_2.b00b0 --> ahb 6GHz
					if [ -e /lib/firmware/qcn6432/caldata_2.b00b0 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_2.b00b0 cal-ahb-soc@0:wifi2@c0000000.bin
					fi
				;;
				ap-mi01.3-c3)
					#caldata_1.b0070 --> ahb 5GHz/6GHz
					if [ -e /lib/firmware/qcn6432/caldata_1.b0070 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0070 cal-ahb-soc@0:wifi1@c0000000.bin
					fi
				;;
				ap-mi04.1)
					#caldata_1.b0052 --> ahb 5GHz
					if [ -e /lib/firmware/qcn6432/caldata_1.b0052 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0052 cal-ahb-soc@0:wifi1@c0000000.bin
					fi

					#caldata_2.b0091 --> ahb 6GHz
					if [ -e /lib/firmware/qcn6432/caldata_2.b0091 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_2.b0091 cal-ahb-soc@0:wifi2@c0000000.bin
					fi
				;;
				ap-mi01.12)
					if [ -e /lib/firmware/qcn6432/caldata_1.b00b0 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b00b0 cal-ahb-soc@0:wifi1@c0000000.bin
					fi
				;;
				ap-mi01.14|ap-mi01.3-c2)
					if [ -e /lib/firmware/qcn6432/caldata_1.b0060 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0060 cal-ahb-soc@0:wifi1@c0000000.bin
					fi
				;;
				ap-mi04.1-c2)
					#caldata_1.b0053 --> ahb 5GHz
					if [ -e /lib/firmware/qcn6432/caldata_1.b0053 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0053 cal-ahb-soc@0:wifi1@c0000000.bin
					fi
				;;
				ap-mi04.3)
					#caldata_1.b0054 --> ahb 5GHz
					if [ -e /lib/firmware/qcn6432/caldata_1.b0054 ]; then
						ln -sf /lib/firmware/qcn6432/caldata_1.b0054 cal-ahb-soc@0:wifi1@c0000000.bin
					fi
				;;
				*)
					#No sym links
				;;
			esac
		fi
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9000 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9000/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/QCN9074/hw1.0/
			cd /lib/firmware/ath11k/QCN9074/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/board-2.bin .
			ln -s /tmp/qcn9000/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/m3.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/amss.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9000/qdss_trace_config.bin .
		fi
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn9100/hw1.0/
			cd /lib/firmware/ath11k/qcn9100/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin .
			ln -s /lib/firmware/qcn9100/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/qdss_trace_config.bin .
		fi
	fi

	if [ -d /lib/firmware/$arch/WIFI_FW/qcn6122 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn6122/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn6122/hw1.0/
			cd /lib/firmware/ath11k/qcn6122/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/board-2.bin .
			ln -s /lib/firmware/qcn6122/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn6122/qdss_trace_config.bin .
		fi
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9100 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin ]; then
			mkdir -p /lib/firmware/ath11k/qcn6122/hw1.0/
			cd /lib/firmware/ath11k/qcn6122/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/board-2.bin .
			ln -s /lib/firmware/qcn9100/caldata*.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9100/qdss_trace_config.bin .
		fi
	elif [ -d /lib/firmware/$arch/WIFI_FW/qcn9224 ]; then
		if [ -e /lib/firmware/$arch/WIFI_FW/qcn9224/board-2.bin ]; then
			mkdir -p /lib/firmware/ath12k/QCN92XX/hw1.0/
			cd /lib/firmware/ath12k/QCN92XX/hw1.0/
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/m3.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/amss.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/amss_dualmac.bin .
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/board-2.bin .
			if [ -e /lib/firmware/$arch/WIFI_FW/qcn9224/regdb.bin ]; then
				ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/regdb.bin .
			fi
			ln -s /lib/firmware/$arch/WIFI_FW/qcn9224/qdss_trace_config.bin .
			case $board_name in
				ap-al02-c4 |\
				ap-al05)
					caldata_symlink_creation "$board_name" "1"
					caldata_symlink_creation "$board_name" "2"
					caldata_symlink_creation "$board_name" "3"
				;;
				ap-al02-c6 |\
				ap-al06 |\
				ap-mi01.2 |\
				ap-mi01.2-c2)
					caldata_symlink_creation "$board_name" "2"
					caldata_symlink_creation "$board_name" "3"
				;;
				ap-al02-c9 |\
				ap-mi01.9)
					caldata_symlink_creation "$board_name" "1"
					caldata_symlink_creation "$board_name" "2"

				;;
				ap-mi01.6)
					caldata_symlink_creation "$board_name" "2"
				;;
				ap-mi01.12 |\
				ap-mi01.14)
					caldata_symlink_creation "$board_name" "3"
				;;
				ap-al02-c20)
					caldata_symlink_creation "$board_name" "1"
					caldata_symlink_creation "$board_name" "2"
					caldata_symlink_creation "$board_name" "3"
					caldata_symlink_creation "$board_name" "4"
				;;
				*)
					#No sym links
				;;
			esac

			case $board_name in
                                rdp466)
                                        caldata_symlink_creation "$board_name" "2"
                                        caldata_symlink_creation "$board_name" "3"
				;;
                                rdp487)
                                        caldata_symlink_creation "$board_name" "2"
				;;
				rdp464)
					caldata_symlink_creation "$board_name" "2"
					caldata_symlink_creation "$board_name" "3"
					caldata_symlink_creation "$board_name" "4"
				;;
				*)
					#No sm links
				;;
                        esac
		fi
	fi

	mkdir -p /vendor/firmware/$arch
	cd /vendor/firmware/$arch && create_soft_link /lib/firmware/$arch/WIFI_FW/Data.msc .
}

mount_adsp_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local ubi_part_name="rootfs"
	local part_name="0:ADSPFW"
	local arch=""

	if mount | grep -q ADSP_FW; then
		return 0
	fi

	arch=$1
	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep ADSPFW | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)
	mkdir -p /lib/firmware/$arch/ADSP_FW

	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		[ -f /rom/lib/firmware/$arch/ADSP_FW/q6_fw.mdt ] && cp /rom/lib/firmware/$arch/ADSP_FW/*.* /lib/firmware/$arch/ADSP_FW/
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		if [ -n "$nor_mtd_part" ]; then
			/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		fi
	elif [ -n "$nand_part" ]; then
		local PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
		ubiattach -p /dev/$PART
		sync
		local ubi_part=$(find_mtd_part adsp_fw 2> /dev/null)
		if [ -n "$ubi_part" ]; then
			/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/ADSP_FW > /dev/console 2>&1
		fi
	fi

	if [ -f /lib/firmware/$arch/ADSP_FW/image/adsp.mdt ]; then
		echo " ADSP FW mount is successful" > /dev/console 2>&1
	fi

	cd  /lib/firmware/$arch &&  ln -s ADSP_FW/image/*.* .
	[ -d /lib/firmware/$arch/ADSP_FW/dspso ] && ln -s /lib/firmware/$arch/ADSP_FW/dspso /dsp
}

mount_bt_fw (){
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local ubi_part_name="rootfs"
	local part_name="0:BTFW"
	local arch=""
	local nor_flash=""
	local nor_mtd_part=""
	local PART=""
	local ubi_part=""

	if mount | grep -q BT_FW; then
		return 0;
	fi

	arch=$1
	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep BTFW | awk '{print $1}' | sed 's/:$//')
	nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part $ubi_part_name 2> /dev/null)

	mkdir -p /lib/firmware/$arch/BT_FW

	if [ -n "$emmc_part" ]; then
		/bin/mount -t squashfs $emmc_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
		[ -f /rom/lib/firmware/$arch/BT_FW/bt_fw.mdt ] && cp /rom/lib/firmware/$arch/BT_FW/*.* /lib/firmware/$arch/BT_FW/
	elif [ -n "$nor_flash" ]; then
		nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		/bin/mount -t squashfs $nor_mtd_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
	elif [ -n "$nand_part" ]; then
		PART=$(grep -w  "$ubi_part_name" /proc/mtd | awk -F: '{print $1}')
		ubiattach -p /dev/$PART
		sync
		ubi_part=$(find_mtd_part bt_fw 2> /dev/null)
		/bin/mount -t squashfs $ubi_part /lib/firmware/$arch/BT_FW > /dev/console 2>&1
	fi

	if [ -f /lib/firmware/$arch/BT_FW/image/bt_fw_patch.mdt ]; then
		echo "BT FW mount is successful" > /dev/console 2>&1
		mkdir /tmp/BT_FW &&  cp -r /lib/firmware/$arch/BT_FW/image/ /tmp/BT_FW
		umount /lib/firmware/$arch/BT_FW
	else
		echo "BT FW mount is failed" > /dev/console 2>&1
	fi

	cd /lib/firmware/$arch && ln -s /tmp/BT_FW/image/*.* .
}

boot() {
 . /lib/functions/system.sh
	local platform=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F[' '/] '{print $1}')
	local board=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $2}')

	if [[ "$platform" == *IPQ807x* ]]; then
		mount_wifi_fw "IPQ8074"
	elif [[ "$platform" == *IPQ8074* ]]; then
		mount_wifi_fw "IPQ8074"
	elif [[ "$platform" == *IPQ9574* ]]; then
		mount_wifi_fw "IPQ9574"
	elif [[ "$platform" == *IPQ6018* ]]; then
		mount_wifi_fw "IPQ6018"
		case "$board" in
			AP-CP01*)
				mount_adsp_fw "IPQ6018"
				;;
		esac
	elif [[ "$platform" == *IPQ5018* ]]; then
		mount_bt_fw "IPQ5018"
		mount_wifi_fw "IPQ5018"
	elif [[ "$platform" == *IPQ5332* ]]; then
		mount_wifi_fw "IPQ5332"
	elif [[ "$platform" == *IPQ5424* ]]; then
		mount_wifi_fw "IPQ5424"
	else
		local emu=$(grep -o "EMULATION" /proc/device-tree/model)
		if [ "$emu" == "EMULATION" ]; then
			mount_wifi_fw "devsoc"
		else
			echo "\nInvalid Target"
		fi
	fi
}

stop_wifi_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local primaryboot=""
	local part_name="0:WIFIFW"
	local wifi_on_rootfs=""
	local nor_flash=""
	arch=$1

	if [[ "$arch" == "IPQ6018" ]] || [[ "$arch" == "IPQ5018" ]] || [[ "$arch" == "IPQ9574" ]] || [[ "$arch" == "IPQ5332" ]] || [[ "$arch" == "IPQ5424" ]]; then
		part_name="rootfs"
		wifi_on_rootfs="1"
	fi

	if [ "$arch" == "IPQ5424" ]; then
                local index=$(get_partname $part_name $arch)
                if [ "$index" == "1" ]; then
                        part_name=${part_name}_${index}
                        ubi_part_name=${part_name}_${index}
                fi
        else
                part_name=$(get_partname_legacy $part_name)
        fi

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep -w "WIFIFW" | awk '{print $1}' | sed 's/:$//')
	if [ -n "$nor_part" ]; then
		nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	fi
	nand_part=$(find_mtd_part $part_name 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/WIFI_FW
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/WIFI_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/WIFI_FW
		if [ -z "$wifi_on_rootfs" ]; then
			local PART=$(grep -w  "WIFIFW" /proc/mtd | awk -F: '{print $1}')
			ubidetach -f -p  /dev/$PART
			sync
		fi
	fi
	if [ -f /lib/firmware/$arch/WIFI_FW/q6_fw.mdt ] || ([ -f /lib/firmware/$arch/WIFI_FW/q6_fw0.mdt ] && [ -f /lib/firmware/$arch/WIFI_FW/q6_fw1.mdt ]); then
		echo " WIFI FW umount not successful" > /dev/console 2>&1
	else
		echo " WIFI FW umount successful" > /dev/console 2>&1
	fi
}

stop_adsp_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local part_name="0:ADSPFW"
	arch=$1

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep ADSPFW | awk '{print $1}' | sed 's/:$//')
	local nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part rootfs 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/ADSP_FW
	elif [ -n "$nor_flash" ]; then
		local nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/ADSP_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/ADSP_FW
	fi
}

stop_bt_fw() {
	local emmc_part=""
	local nand_part=""
	local nor_part=""
	local part_name="0:BTFW"
	local nor_mtd_part=""
	local nor_flash=""
	arch=$1

	emmc_part=$(find_mmc_part $part_name 2> /dev/null)
	nor_part=$(cat /proc/mtd | grep BTFW | awk '{print $1}' | sed 's/:$//')
	nor_flash=`find /sys/bus/spi/devices/*/mtd -name ${nor_part}`
	nand_part=$(find_mtd_part rootfs 2> /dev/null)
	if [ -n "$emmc_part" ]; then
		umount /lib/firmware/$arch/BT_FW
	elif [ -n "$nor_flash" ]; then
		nor_mtd_part=$(find_mtd_part $part_name 2> /dev/null)
		umount /lib/firmware/$arch/BT_FW
	elif [ -n "$nand_part" ]; then
		umount /lib/firmware/$arch/BT_FW
	fi
}

stop() {
	local platform=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F[' '/] '{print $1}')
	local board=$(grep -o "IPQ.*" /proc/device-tree/model | awk -F/ '{print $2}')

	if [ "$platform" == "IPQ807x" ]; then
		stop_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ8074" ]; then
		stop_wifi_fw "IPQ8074"
	elif [ "$platform" == "IPQ9574" ]; then
		stop_wifi_fw "IPQ9574"
	elif [ "$platform" == "IPQ6018" ]; then
		stop_wifi_fw "IPQ6018"
		case "$board" in
			AP-CP01*)
				stop_adsp_fw "IPQ6018"
				;;
		esac
	elif [ "$platform" == "IPQ5018" ]; then
		stop_wifi_fw "IPQ5018"
		stop_bt_fw "IPQ5018"
	elif [ "$platform" == "IPQ5332" ]; then
		stop_wifi_fw "IPQ5332"
	elif [ "$platform" == "IPQ5424" ]; then
		stop_wifi_fw "IPQ5424"
	else
		local emu=$(grep -o "EMULATION" /proc/device-tree/model)
		if [ "$emu" == "EMULATION" ]; then
			stop_wifi_fw "devsoc"
		else
			echo "\nInvalid Target"
			return 0
		fi
	fi
	return 0
}
