###################################################
# Makefile for aquantia github driver
###################################################
TARGET := aqr-phy
obj-m += $(TARGET).o
$(TARGET)-objs := ./aquantia_main.o \
		./aquantia_hwmon.o
